-- Seed default plans with proper UUID format
-- Note: Using readable UUIDs for easier reference in documentation and testing
-- In production, use proper random UUIDs generated by uuid.New().String()

-- PostgreSQL compatible seed

INSERT INTO plans (id, name, slug, price, billing_period, features, limits, is_active, created_at, updated_at, deleted_at) VALUES
('550e8400-e29b-41d4-a716-446655440001', 'Free', 'free', 0.00, 'monthly', 
 '{"storage": "1GB", "users": "1", "support": "Community"}',
 '{"api_calls_per_month": 1000, "max_users": 1, "storage_gb": 1}',
 TRUE, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, NULL),
 
('550e8400-e29b-41d4-a716-446655440002', 'Pro', 'pro', 29.00, 'monthly',
 '{"storage": "50GB", "users": "10", "support": "Email"}',
 '{"api_calls_per_month": 100000, "max_users": 10, "storage_gb": 50}',
 TRUE, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, NULL),
 
('550e8400-e29b-41d4-a716-446655440003', 'Enterprise', 'enterprise', 99.00, 'monthly',
 '{"storage": "Unlimited", "users": "Unlimited", "support": "Priority"}',
 '{"api_calls_per_month": -1, "max_users": -1, "storage_gb": -1}',
 TRUE, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, NULL);

-- Sample organization with UUID
INSERT INTO organizations (id, name, slug, created_at, updated_at, deleted_at) VALUES
('650e8400-e29b-41d4-a716-446655440001', 'Demo Organization', 'demo-org', (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, NULL);

-- Sample user with UUID (password: password123)
-- Password hash generated with: bcrypt.GenerateFromPassword([]byte("password123"), bcrypt.DefaultCost)
-- Email verified for demo user (verification_token is NULL after verification)
INSERT INTO users (id, name, email, password, email_verified, email_verified_at, verification_token, refresh_token, refresh_token_expires_at, organization_id, created_at, updated_at, deleted_at) VALUES
('750e8400-e29b-41d4-a716-446655440001', 'Demo User', 'demo@example.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', TRUE, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, NULL, NULL, NULL, '650e8400-e29b-41d4-a716-446655440001', (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, NULL);

-- Assign user to organization as owner
INSERT INTO organization_members (organization_id, user_id, role, joined_at, deleted_at) VALUES
('650e8400-e29b-41d4-a716-446655440001', '750e8400-e29b-41d4-a716-446655440001', 'owner', (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, NULL);

-- Free subscription for demo organization
-- Period: 30 days from now (2592000 seconds = 30 days)
INSERT INTO subscriptions (id, organization_id, plan_id, status, current_period_start, current_period_end, created_at, updated_at, deleted_at) VALUES
('850e8400-e29b-41d4-a716-446655440001', '650e8400-e29b-41d4-a716-446655440001', '550e8400-e29b-41d4-a716-446655440001', 'active', (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, ((EXTRACT(EPOCH FROM NOW()) + 2592000) * 1000)::BIGINT, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT, NULL);

-- Display seeded credentials
SELECT '
========================================
✅ Database seeded successfully!
========================================

Demo Credentials:
  Email:    demo@example.com
  Password: password123
  
Organization:
  Name:     Demo Organization
  Slug:     demo-org
  
Plan:
  Type:     Free
  Price:    $0/month
  
Test the API:
  curl -X POST http://localhost:3000/api/v1/auth/login \\
    -H "Content-Type: application/json" \\
    -d "{\"email\":\"demo@example.com\",\"password\":\"password123\"}"
    
UUIDs Used:
  Plans:        550e8400-e29b-41d4-a716-44665544000[1-3]
  Organization: 650e8400-e29b-41d4-a716-446655440001
  User:         750e8400-e29b-41d4-a716-446655440001
  Subscription: 850e8400-e29b-41d4-a716-446655440001
  
========================================
' AS 'Seed Information';
